// Generated by CoffeeScript 2.7.0
/*
Introducing, Grab a Cup of Coffee Before Work.

Written in Coffeescript and compiled to Javascript.

My first ever beginner's Coffeescript project, I'm still learning the language lol.

Written by Ethan J.

Just your typical morning before work, gotta grab your only source of energy, coffee.

I only wrote this in Coffeescript for the punchline.
*/
var coffee, decaf, espresso, exit, hell, milk, nope, nothing, prompt, soda, water;

// mornin, pick a drink
prompt = require("prompt-sync")();

// what coffee
espresso = prompt("What coffee? ");

coffee = function() {
  console.log("Pouring a cup of", espresso, "...");
  return console.log("Done!");
};

coffee();

if (espresso === "espresso") {
  console.log("I feel successfully caffeinated.");
}

// I think you gave me decaf
decaf = function() {
  console.log("I feel exhausted, and now I want some π. Did you give me decaf?");
  return decaf = prompt("Did you? ");
};

if (espresso !== "espresso" && espresso !== "piss" && espresso !== "pee") {
  decaf();
}

// secret ending
hell = function() {
  return console.log("Why the hell is there piss in my cup? is this a drug test?");
};

if (espresso === "piss" || espresso === "pee") {
  hell();
}

// secret ending 2
soda = function() {
  return console.log("I wanted coffee, but soda's acceptable too...");
};

if (espresso === "soda") {
  soda();
}

// secret ending 3
water = function() {
  return console.log("I wanted coffee, not water...");
};

if (espresso === "water") {
  water();
}

// secret ending 4
milk = function() {
  return console.log("Oh cool, milk.");
};

if (espresso === "milk") {
  milk();
}

// nothing?
nothing = function() {
  return console.log("What am I going to drink now?");
};

if (espresso === " ") {
  nothing();
}

if (decaf === "Yes." || decaf === "yes" || decaf === "yes." || decaf === "Yes" || decaf === "ye" || decaf === "Ye") {
  // you did?
  console.log("How dare you!");
}

nope = function() {
  console.log("Really?");
  console.log("So you gave me", espresso, "?");
  return console.log("ok, then");
};

if (decaf === "No." || decaf === "no" || decaf === "no." || decaf === "No") {
  nope();
}

exit = function() {
  return console.log("Program Exit.");
};

setTimeout(exit, 3000);
